const express = require('express');
const attendanceRoutes = require('./attendanceRoutes.js');
const classRoutes = require('./classRoutes.js');
const courseDetailRoutes = require('./courseDetailRoutes.js');
const courseRoutes = require('./courseRoutes.js');
const feedbackTeacherRoutes = require('./feedbackTeacherRoutes.js');
const feedbackCourseRoutes = require('./feedbackCourseRoutes.js');
const profileRoutes = require('./profileRoutes.js');
const roleRoutes = require('./roleRoutes.js');
const scheduleRoutes = require('./scheduleRoutes.js');
const testRoutes = require('./testRoutes.js');
const testSubmissionRoutes = require('./testSubmissionRoutes.js');
const userRoutes = require('./userRoutes.js');
const testAssignRoutes = require('./testAssignRoutes.js');
const paymentRoutes = require('./paymentRoutes.js');
const enrollmentRoutes = require('./enrollmentRoutes.js');
const eventDataRoutes = require('./eventDataRoutes.js');
const learningMaterialRoutes = require('./learningMaterialRoutes.js');
const customerConsultingRoutes = require('./customerConsultingRoutes.js');

const router = express.Router();
router.use('/payments', paymentRoutes);
router.use('/classes', classRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/learningMaterials', learningMaterialRoutes);
router.use('/courseDetail', courseDetailRoutes);
router.use('/courses', courseRoutes);
router.use('/feedbacksTeacher', feedbackTeacherRoutes);
router.use('/feedbacksCourse', feedbackCourseRoutes);
router.use('/profiles', profileRoutes);
router.use('/roles', roleRoutes);
router.use('/schedule', scheduleRoutes);
router.use('/tests', testRoutes);
router.use('/testSubmission', testSubmissionRoutes);
router.use('/test-assigns', testAssignRoutes);
router.use('/customerConsultings', customerConsultingRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/users', userRoutes);
router.use('/eventsData', eventDataRoutes);

module.exports=router;